### ISSUE TITLE
Include Source Code for Bloop/Blaza Mod

### ISSUE THREAD

**Issue by jet082** [LeeTwentyThree/SubnauticaMods#1]
The Bloop/Blaza mod has been floating around the internet for awhile now. It would be nice to see the source code (and to get it updated for 2.0).

**Comment by LeeTwentyThree** [comment]
Uploaded legacy source code. 2.0 port coming after ECC Library upgrade.

https://github.com/LeeTwentyThree/Lee23-LegacySubnauticaMods/tree/main/Socksfor1Monsters
